name: NetPositive
description: A podcast about activism & technology
url: http://netposi.com
permalink: /:categories/:title
img_dir: "/assets/img/"
contact:
  twitter: "netposi"
  email: "info@netposi.com"
  github:
  phone:
  fax:
yourname: Net Positive
feed: 'http://example.com/feed'
year: 2015
