name: NetPositive
description: A podcast about activism & technology
url: http://andreadelrio.github.io/netpositive/
permalink: /:categories/:title
img_dir: "/assets/img/"
contact:
  twitter: netposi
  email: info@netposi.com
  github: https://github.com/drewrwilson/netpositive/
  phone:
  fax:
yourname: NetPositive
year: 2015
